azure-information-protection-schema.md
MicrosoftDocs/office-365-management-api pull request #306
Opened 2022-09-12 03:44 UTC by krishnacloud123

Created .md page for AIP Schema for events (93 , 94 , 97). @lindalu-MSFT

2022-09-12 03:45 UTC, opbld30 commented
Docs Build status updates of commit _[0dfaa08](https://github.com/krishnacloud123/office-365-management-api/commits/0dfaa087a5f3037be55b55759f4d1689f3d55c38)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[azure-information-protection-schema.md](https://github.com/krishnacloud123/office-365-management-api/blob/patch-2/azure-information-protection-schema.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/5bf2d4aa-8241-3e63-8951-f50a5c143d97/202209120344442112-306/BuildReport?accessString=5e249994cfcc9f94330e8fe958d3f576f36b0740e63a785c0053b74f89f24964).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/5bf2d4aa-8241-3e63-8951-f50a5c143d97?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-12 19:07 UTC, lindalu-MSFT requested changes
Hi, I added the metadata at the top and bookmarks. There is no content for events 95 and 96, is that intentional or are they in the wrong locations in this topic? Let me know if you have questions.

2022-09-12 19:07 UTC, lindalu-MSFT commented on azure-information-protection-schema.md
> +## AipFileDeleted.
```suggestion
## AipFileDeleted
```

2022-09-12 19:24 UTC, krishnacloud123 commented
> Hi, I added the metadata at the top and bookmarks. There is no content for events 95 and 96, is that intentional or are they in the wrong locations in this topic? Let me know if you have questions.

95 and 96 is WIP and looking to get it completed and update the document at the earliest.

2022-09-14 20:47 UTC, krishnacloud123 commented
Just wanted to check if there are any more pending items for one this – before the document can be published.

Krishna ***@***.***)
Cloud Solution Architect

From: Linda Lu Cannon ***@***.***>
Sent: Monday, September 12, 2022 3:08 PM
To: MicrosoftDocs/office-365-management-api ***@***.***>
Cc: Krishna V ***@***.***>; Author ***@***.***>
Subject: Re: [MicrosoftDocs/office-365-management-api] azure-information-protection-schema.md (PR #306)


@lindalu-MSFT requested changes on this pull request.

Hi, I added the metadata at the top and bookmarks. There is no content for events 95 and 96, is that intentional or are they in the wrong locations in this topic? Let me know if you have questions.

________________________________

In azure-information-protection-schema.md<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Foffice-365-management-api%2Fpull%2F306%23discussion_r968765099&data=05%7C01%7CKrishnaswamy.Venkataraman%40microsoft.com%7C5b2579fca3224546788708da94f21e48%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637986064880933439%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=wvBraveYnxiOES1LayGDqx54wu3t6LZAtfxuvWoen94%3D&reserved=0>:

> @@ -0,0 +1,164 @@



+


⬇️ Suggested change

-



+---



+ms.subservice: office-365-service-communications-api



+ms.TocTitle: Office 365 Management Activity API schema



+title: Azure Information Protection (AIP) scanner events



+description: Audit events from the AIP Unified Labeling client



+ms.ContentId: 4c8793f3-d0b4-4d62-87b4-931cc31d99f5



+ms.topic: reference (API)



+ms.date: 09/12/2022



+ms.localizationpriority: high



+---



________________________________

In azure-information-protection-schema.md<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Foffice-365-management-api%2Fpull%2F306%23discussion_r968767238&data=05%7C01%7CKrishnaswamy.Venkataraman%40microsoft.com%7C5b2579fca3224546788708da94f21e48%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637986064880933439%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=tZNyhxxXR9EizX%2BJNJ60zydZWEe6SoQC580tLEXMDd8%3D&reserved=0>:

> @@ -0,0 +1,164 @@



+



+## AipDiscover


⬇️ Suggested change

-## AipDiscover



________________________________

In azure-information-protection-schema.md<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Foffice-365-management-api%2Fpull%2F306%23discussion_r968767610&data=05%7C01%7CKrishnaswamy.Venkataraman%40microsoft.com%7C5b2579fca3224546788708da94f21e48%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637986064881089679%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=n7faMz8%2BjKL4%2Frepfmtg%2Bjbjgx7LTiFS462g9MDtUxo%3D&reserved=0>:

> @@ -0,0 +1,164 @@



+



+## AipDiscover



+



+# AIP-Audit-schema-details


⬇️ Suggested change

-# AIP-Audit-schema-details



________________________________

In azure-information-protection-schema.md<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Foffice-365-management-api%2Fpull%2F306%23discussion_r968767749&data=05%7C01%7CKrishnaswamy.Venkataraman%40microsoft.com%7C5b2579fca3224546788708da94f21e48%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637986064881089679%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=nEIoo4fnZ%2Bu74%2BjvAbrIceLKsEFpKIlg3GPV7EM4ByA%3D&reserved=0>:

> @@ -0,0 +1,164 @@



+



+## AipDiscover



+



+# AIP-Audit-schema-details



+## Azure Information Protection (AIP) scanner events


⬇️ Suggested change

-## Azure Information Protection (AIP) scanner events



+# Azure Information Protection (AIP) scanner events



________________________________

In azure-information-protection-schema.md<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Foffice-365-management-api%2Fpull%2F306%23discussion_r968768004&data=05%7C01%7CKrishnaswamy.Venkataraman%40microsoft.com%7C5b2579fca3224546788708da94f21e48%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637986064881245909%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=kN6MsetWkl%2BqHMwS7aYgT6Ex6Q6HpoIwS4KPQFxVz00%3D&reserved=0>:

> @@ -0,0 +1,164 @@



+



+## AipDiscover



+



+# AIP-Audit-schema-details



+## Azure Information Protection (AIP) scanner events



+



+Audit events from the AIP Unified Labeling client


⬇️ Suggested change

-Audit events from the AIP Unified Labeling client



This is either a sentence fragment or a redundant heading. Suggest deleting.

________________________________

In azure-information-protection-schema.md<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Foffice-365-management-api%2Fpull%2F306%23discussion_r968770877&data=05%7C01%7CKrishnaswamy.Venkataraman%40microsoft.com%7C5b2579fca3224546788708da94f21e48%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637986064881245909%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=86qi%2BHySC7znHfBI9KB1Gu%2BMJ0pJMYQi7Oyy009WTJE%3D&reserved=0>:

> @@ -0,0 +1,164 @@



+



+## AipDiscover



+



+# AIP-Audit-schema-details



+## Azure Information Protection (AIP) scanner events



+



+Audit events from the AIP Unified Labeling client



+The AIP Unified Labeling client includes the Add-in for Office, the Scanner, the Viewer for Windows, the client PowerShell, and the Classify-and-Protect shell extension for Windows. All these components generate audit events that show up in the Office 365 activity logs and can be queried using the Office 365 Management Activity API. [click here](https://docs.microsoft.com/en-us/office/office-365-management-api/office-365-management-activity-api-reference)


⬇️ Suggested change

-The AIP Unified Labeling client includes the Add-in for Office, the Scanner, the Viewer for Windows, the client PowerShell, and the Classify-and-Protect shell extension for Windows. All these components generate audit events that show up in the Office 365 activity logs and can be queried using the Office 365 Management Activity API. [click here](https://docs.microsoft.com/en-us/office/office-365-management-api/office-365-management-activity-api-reference)



+The AIP Unified Labeling client includes the Add-in for Office, the Scanner, the Viewer for Windows, the client PowerShell, and the Classify-and-Protect shell extension for Windows. All these components generate audit events that appear in the Office 365 activity logs and can be queried using the Office 365 Management Activity API. For more information, see the [Office 365 Management Activity API reference](/office/office-365-management-api/office-365-management-activity-api-reference)



________________________________

In azure-information-protection-schema.md<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Foffice-365-management-api%2Fpull%2F306%23discussion_r968777374&data=05%7C01%7CKrishnaswamy.Venkataraman%40microsoft.com%7C5b2579fca3224546788708da94f21e48%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637986064881245909%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=uinKu6nunMfKb05jibk62izXjf0vFX3l9jAUz3JA0OM%3D&reserved=0>:

> +Azure Information Protection (AIP) scanner events related to  Scanner events related to



+



+| Column | Potential Value | Description |



+|:--|:--|:--|



+|ClientIP| 20.237.230.167|The IP address of the device that was used when the activity was logged. The IP address is displayed in either an IPv4 or IPv6 address format.  For some services, the value displayed in this property mi [...]

2022-09-14 22:26 UTC, opbld33 commented
Docs Build status updates of commit _[c7be791](https://github.com/krishnacloud123/office-365-management-api/commits/c7be79151ae431964b240fd10af1f499c9314966)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[azure-information-protection-schema.md](https://github.com/krishnacloud123/office-365-management-api/blob/patch-2/azure-information-protection-schema.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/5bf2d4aa-8241-3e63-8951-f50a5c143d97/202209142225524491-306/BuildReport?accessString=9dd61b1fdb587e364c62768e5472db6437c5cca06c746db2a2eee19bb95be8fb).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/5bf2d4aa-8241-3e63-8951-f50a5c143d97?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-14 22:35 UTC, opbld31 commented
Docs Build status updates of commit _[e4f9c01](https://github.com/krishnacloud123/office-365-management-api/commits/e4f9c01ae9ba08f6c2c4df64570c66d862d10942)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[azure-information-protection-schema.md](https://github.com/krishnacloud123/office-365-management-api/blob/patch-2/azure-information-protection-schema.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/5bf2d4aa-8241-3e63-8951-f50a5c143d97/202209142234558292-306/BuildReport?accessString=916488e4d852838e452b961e052d2a94b0527c5bd41d947c18080d29e51e36e1).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/5bf2d4aa-8241-3e63-8951-f50a5c143d97?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-14 22:36 UTC, opbld33 commented
Docs Build status updates of commit _[9ed2aeb](https://github.com/krishnacloud123/office-365-management-api/commits/9ed2aebe48f51fb99f33a37ac229e0201dbc0791)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[azure-information-protection-schema.md](https://github.com/krishnacloud123/office-365-management-api/blob/patch-2/azure-information-protection-schema.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/5bf2d4aa-8241-3e63-8951-f50a5c143d97/202209142235078784-306/BuildReport?accessString=2e9671484c0f4f376e1e48d1503f13135b08e6932d577541be4b86c939ccabff).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/5bf2d4aa-8241-3e63-8951-f50a5c143d97?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-14 22:37 UTC, opbld32 commented
Docs Build status updates of commit _[5c63a75](https://github.com/krishnacloud123/office-365-management-api/commits/5c63a75897a50fc4f7dd2f2fab7b04c6f60a7090)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[azure-information-protection-schema.md](https://github.com/krishnacloud123/office-365-management-api/blob/patch-2/azure-information-protection-schema.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/5bf2d4aa-8241-3e63-8951-f50a5c143d97/202209142236428051-306/BuildReport?accessString=c7653932ff42ef284ea2cc72782db2be05d042be94ff278ca034b550408ea637).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/5bf2d4aa-8241-3e63-8951-f50a5c143d97?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-14 22:43 UTC, opbld32 commented
Docs Build status updates of commit _[8aa3924](https://github.com/krishnacloud123/office-365-management-api/commits/8aa3924e36a52da557ac6def89469ebe6bac1f70)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[azure-information-protection-schema.md](https://github.com/krishnacloud123/office-365-management-api/blob/patch-2/azure-information-protection-schema.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/5bf2d4aa-8241-3e63-8951-f50a5c143d97/202209142242159087-306/BuildReport?accessString=242d5a1ca7db55e328f1e40c789908a30cf080066993fd7d925e8fda2f9cf602).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/5bf2d4aa-8241-3e63-8951-f50a5c143d97?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-14 22:44 UTC, opbld31 commented
Docs Build status updates of commit _[e794973](https://github.com/krishnacloud123/office-365-management-api/commits/e79497335402fe2e54ad6a873946e01c44e62f3b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[azure-information-protection-schema.md](https://github.com/krishnacloud123/office-365-management-api/blob/patch-2/azure-information-protection-schema.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/5bf2d4aa-8241-3e63-8951-f50a5c143d97/202209142242416620-306/BuildReport?accessString=f07136f6286741c9a018b1c7178a12c5ba863abedb0a3f61b8ab995547768c9d).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/5bf2d4aa-8241-3e63-8951-f50a5c143d97?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-14 22:44 UTC, opbld30 commented
Docs Build status updates of commit _[ae2b3df](https://github.com/krishnacloud123/office-365-management-api/commits/ae2b3df678f1ab4dfaa398ccbeacf8a5cb2f2a22)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[azure-information-protection-schema.md](https://github.com/krishnacloud123/office-365-management-api/blob/patch-2/azure-information-protection-schema.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/5bf2d4aa-8241-3e63-8951-f50a5c143d97/202209142243580639-306/BuildReport?accessString=2b46a1c0b7931262a70e10871fe9be57e3e30fc31285297b49ac7ea6b06db907).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/5bf2d4aa-8241-3e63-8951-f50a5c143d97?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-15 04:42 UTC, lindalu-MSFT commented
Do you need a quick phone call to discuss this PR? I see lots of commits that are not in your branch and all the revisions I requested are still there. I’d be happy to discuss these changes with you and we can get this published.

From: krishna ***@***.***>
Sent: Wednesday, September 14, 2022 1:48 PM
To: MicrosoftDocs/office-365-management-api ***@***.***>
Cc: Linda Lu Cannon ***@***.***>; Mention ***@***.***>
Subject: Re: [MicrosoftDocs/office-365-management-api] azure-information-protection-schema.md (PR #306)

Just wanted to check if there are any more pending items for one this – before the document can be published.

Krishna ***@***.***<mailto:***@***.***>)
Cloud Solution Architect

From: Linda Lu Cannon ***@***.***<mailto:***@***.***>>
Sent: Monday, September 12, 2022 3:08 PM
To: MicrosoftDocs/office-365-management-api ***@***.***<mailto:***@***.***>>
Cc: Krishna V ***@***.***<mailto:***@***.***>>; Author ***@***.***<mailto:***@***.***>>
Subject: Re: [MicrosoftDocs/office-365-management-api] azure-information-protection-schema.md (PR #306)


@lindalu-MSFT requested changes on this pull request.

Hi, I added the metadata at the top and bookmarks. There is no content for events 95 and 96, is that intentional or are they in the wrong locations in this topic? Let me know if you have questions.

________________________________

In azure-information-protection-schema.md<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Foffice-365-management-api%2Fpull%2F306%23discussion_r968765099&data=05%7C01%7CKrishnaswamy.Venkataraman%40microsoft.com%7C5b2579fca3224546788708da94f21e48%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637986064880933439%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=wvBraveYnxiOES1LayGDqx54wu3t6LZAtfxuvWoen94%3D&reserved=0>:

> @@ -0,0 +1,164 @@



+


⬇️ Suggested change

-



+---



+ms.subservice: office-365-service-communications-api



+ms.TocTitle: Office 365 Management Activity API schema



+title: Azure Information Protection (AIP) scanner events



+description: Audit events from the AIP Unified Labeling client



+ms.ContentId: 4c8793f3-d0b4-4d62-87b4-931cc31d99f5



+ms.topic: reference (API)



+ms.date: 09/12/2022



+ms.localizationpriority: high



+---



________________________________

In azure-information-protection-schema.md<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Foffice-365-management-api%2Fpull%2F306%23discussion_r968767238&data=05%7C01%7CKrishnaswamy.Venkataraman%40microsoft.com%7C5b2579fca3224546788708da94f21e48%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637986064880933439%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=tZNyhxxXR9EizX%2BJNJ60zydZWEe6SoQC580tLEXMDd8%3D&reserved=0>:

> @@ -0,0 +1,164 @@



+



+## AipDiscover


⬇️ Suggested change

-## AipDiscover



________________________________

In azure-information-protection-schema.md<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Foffice-365-management-api%2Fpull%2F306%23discussion_r968767610&data=05%7C01%7CKrishnaswamy.Venkataraman%40microsoft.com%7C5b2579fca3224546788708da94f21e48%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637986064881089679%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=n7faMz8%2BjKL4%2Frepfmtg%2Bjbjgx7LTiFS462g9MDtUxo%3D&reserved=0>:

> @@ -0,0 +1,164 @@



+



+## AipDiscover



+



+# AIP-Audit-schema-details


⬇️ Suggested change

-# AIP-Audit-schema-details



________________________________

In azure-information-protection-schema.md<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Foffice-365-management-api%2Fpull%2F306%23discussion_r968767749&data=05%7C01%7CKrishnaswamy.Venkataraman%40microsoft.com%7C5b2579fca3224546788708da94f21e48%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637986064881089679%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=nEIoo4fnZ%2Bu74%2BjvAbrIceLKsEFpKIlg3GPV7EM4ByA%3D&reserved=0>:

> @@ -0,0 +1,164 @@



+



+## AipDiscover



+



+# AIP-Audit-schema-details



+## Azure Information Protection (AIP) scanner events


⬇️ Suggested change

-## Azure Information Protection (AIP) scanner events



+# Azure Information Protection (AIP) scanner events



________________________________

In azure-information-protection-schema.md<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Foffice-365-management-api%2Fpull%2F306%23discussion_r968768004&data=05%7C01%7CKrishnaswamy.Venkataraman%40microsoft.com%7C5b2579fca3224546788708da94f21e48%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637986064881245909%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=kN6MsetWkl%2BqHMwS7aYgT6Ex6Q6HpoIwS4KPQFxVz00%3D&reserved=0>:

> @@ -0,0 +1,164 @@



+



+## AipDiscover



+



+# AIP-Audit-schema-details



+## Azure Information Protection (AIP) scanner events



+



+Audit events from the AIP Unified Labeling client


⬇️ Suggested change

-Audit events from the AIP Unified Labeling client



This is either a sentence fragment or a redundant heading. Suggest deleting.

________________________________

In azure-information-protection-schema.md<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Foffice-365-management-api%2Fpull%2F306%23discussion_r968770877&data=05%7C01%7CKrishnaswamy.Venkataraman%40microsoft.com%7C5b2579fca3224546788708da94f21e48%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637986064881245909%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=86qi%2BHySC7znHfBI9KB1Gu%2BMJ0pJMYQi7Oyy009WTJE%3D&reserved=0>:

> @@ -0,0 +1,164 @@



+



+## AipDiscover



+



+# AIP-Audit-schema-details



+## Azure Information Protection (AIP) scanner events



+



+Audit events from the AIP Unified Labeling client



+The AIP Unified Labeling client includes the Add-in for Office, the Scanner, the Viewer for Windows, the client PowerShell, and the Classify-and-Protect shell extension for Windows. All these components generate audit events that show up in the Office 365 activity logs and can be queried using the Office 365 Management Activity API. [click here](https://docs.microsoft.com/en-us/office/office-365-management-api/office-365-management-activity-api-reference)


⬇️ Suggested change

-The AIP Unified Labeling client includes the Add-in for Office, the Scanner, the Viewer for Windows, the client PowerShell, and the Classify-and-Protect shell extension for Windows. All these components generate audit events that show up in the Office 365 activity logs and can be queried using the Office 365 Management Activity API. [click here](https://docs.microsoft.com/en-us/office/office-365-management-api/office-365-management-activity-api-reference)



+The AIP Unified Labeling client includes the Add-in for Office, the Scanner, the Viewer for Windows, the client PowerShell, and the Classify-and-Protect shell extension for Windows. All these components generate audit events that appear in the Office 365 activity logs and can be queried using the Office 365 Management Activity API. For more information, see the [Office 365 Management Activity API reference](/office/office-365-management-api/office-365-management-activity-api-reference)



________________________________

In azure-information-protection-schema.md<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Foffice-365-management-api%2Fpull%2F306%23discussion_r968777374&data=05%7C01%7CKrishnaswamy.Venkataraman%40microsoft.com%7C5b2579fca3224546788708da94f21e48%7C72f988bf86 [...]

2022-09-27 20:47 UTC, opbld33 commented
Docs Build status updates of commit _[5238f3a](https://github.com/krishnacloud123/office-365-management-api/commits/5238f3a560c07e1c1ae2927d753c07e00fde8aa4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[azure-information-protection-schema.md](https://github.com/krishnacloud123/office-365-management-api/blob/patch-2/azure-information-protection-schema.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/5bf2d4aa-8241-3e63-8951-f50a5c143d97/202209272046067539-306/BuildReport?accessString=102194357af0dc2b4cef3114916fe638df4253ad39f93447778181353374373b).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/5bf2d4aa-8241-3e63-8951-f50a5c143d97?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-27 20:50 UTC, opbld33 commented
Docs Build status updates of commit _[4e81aea](https://github.com/krishnacloud123/office-365-management-api/commits/4e81aea71f753fc9ef8d9a914a6b8b5a52042c95)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[azure-information-protection-schema.md](https://github.com/krishnacloud123/office-365-management-api/blob/patch-2/azure-information-protection-schema.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/5bf2d4aa-8241-3e63-8951-f50a5c143d97/202209272048529082-306/BuildReport?accessString=7e79137965e912764597027f4f393787f78396d20d48dfc73010ff00c9d630b0).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/5bf2d4aa-8241-3e63-8951-f50a5c143d97?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-27 20:51 UTC, opbld33 commented
Docs Build status updates of commit _[6118868](https://github.com/krishnacloud123/office-365-management-api/commits/6118868dbf3445cfecffec52dc25cca7989b3921)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[azure-information-protection-schema.md](https://github.com/krishnacloud123/office-365-management-api/blob/patch-2/azure-information-protection-schema.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/5bf2d4aa-8241-3e63-8951-f50a5c143d97/202209272050288977-306/BuildReport?accessString=f465c39e87e6d031a608c46f1c9cdc1c1050664677742858281d68d7bc9e419e).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/5bf2d4aa-8241-3e63-8951-f50a5c143d97?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-27 20:52 UTC, opbld31 commented
Docs Build status updates of commit _[6131f09](https://github.com/krishnacloud123/office-365-management-api/commits/6131f0900886ebd6d042af9028bfabf9857fcdb2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[azure-information-protection-schema.md](https://github.com/krishnacloud123/office-365-management-api/blob/patch-2/azure-information-protection-schema.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/5bf2d4aa-8241-3e63-8951-f50a5c143d97/202209272051189564-306/BuildReport?accessString=7a968d4ecb1ec30acf1584c86cef099b5e0f4445c178f08a1783161dfa999367).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/5bf2d4aa-8241-3e63-8951-f50a5c143d97?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-27 20:53 UTC, opbld32 commented
Docs Build status updates of commit _[2cf0e1c](https://github.com/krishnacloud123/office-365-management-api/commits/2cf0e1c65422066a87568b0d19ebe8588c95b748)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[azure-information-protection-schema.md](https://github.com/krishnacloud123/office-365-management-api/blob/patch-2/azure-information-protection-schema.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/5bf2d4aa-8241-3e63-8951-f50a5c143d97/202209272052340065-306/BuildReport?accessString=de657aba2453d6faf60f9fdc3120fc28c10b5a1338a33d1e56e5442ba0491e2b).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/5bf2d4aa-8241-3e63-8951-f50a5c143d97?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-27 20:54 UTC, opbld31 commented
Docs Build status updates of commit _[d64fd8f](https://github.com/krishnacloud123/office-365-management-api/commits/d64fd8fa781e2c8b9f414d90532727adc0a64e12)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[azure-information-protection-schema.md](https://github.com/krishnacloud123/office-365-management-api/blob/patch-2/azure-information-protection-schema.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/5bf2d4aa-8241-3e63-8951-f50a5c143d97/202209272053173047-306/BuildReport?accessString=942c4d4947e062293620ebbe7fbf1805683c60623914209fc33064d6d8ee1ad8).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/5bf2d4aa-8241-3e63-8951-f50a5c143d97?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-27 20:55 UTC, opbld33 commented
Docs Build status updates of commit _[096bb6e](https://github.com/krishnacloud123/office-365-management-api/commits/096bb6ee793e65720d88eb432e0a09de10058dc7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[azure-information-protection-schema.md](https://github.com/krishnacloud123/office-365-management-api/blob/patch-2/azure-information-protection-schema.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/5bf2d4aa-8241-3e63-8951-f50a5c143d97/202209272053519674-306/BuildReport?accessString=e554e07f35e25e4f4cbedba902a81b5157821dc3b36768b58486ad44cb18f42b).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/5bf2d4aa-8241-3e63-8951-f50a5c143d97?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-27 20:56 UTC, opbld33 commented
Docs Build status updates of commit _[d5194b0](https://github.com/krishnacloud123/office-365-management-api/commits/d5194b07b6bc26c4fc4378af8860007ab1ce5cbd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[azure-information-protection-schema.md](https://github.com/krishnacloud123/office-365-management-api/blob/patch-2/azure-information-protection-schema.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/5bf2d4aa-8241-3e63-8951-f50a5c143d97/202209272054476781-306/BuildReport?accessString=1efef01731d289d0ade7c58ee57dd70052f85cc2a83b4f7aa75032750052a4db).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/5bf2d4aa-8241-3e63-8951-f50a5c143d97?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-27 20:57 UTC, lindalu-MSFT approved these changes

2022-09-27 20:57 UTC, merged

2022-09-27 20:57 UTC, opbld33 commented
Docs Build status updates of commit _[df808b2](https://github.com/krishnacloud123/office-365-management-api/commits/df808b25e0d164a2a80b4f72e9e32195b1e091b5)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-2ad5dc37)

<a id="2ad5dc37"></a>
###
 - **[Error: GitBranchDeletedOrForcePushed]** 
`````
Cannot sync git repo to specified commit because ref +refs/pull/306/merge has been deleted or has been force pushed.
 If this is pull request, please ensure it is mergeable (no merge conflict) and open (not closed).
`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/5bf2d4aa-8241-3e63-8951-f50a5c143d97/202209272056100337-306/BuildReport?accessString=90a894117302a5379f996364161e8c1559efd3cf0b7df5d9c105da4b3f44d7a7).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/5bf2d4aa-8241-3e63-8951-f50a5c143d97?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>